### ISSUE TITLE
The AMI should be publicly available

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur-ami#3]
"publicly available" means two things, as described here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html

* it needs to be shared to all the regions that will use it. (I don't know whether this actually means **all** regions, because I believe some are special: China, some US gov't regions, maybe others).
* it needs to have its `launchPermission` property set appropriately

**Comment by dustinmm80** [comment]
Closing this, created #9 as a followup to get the AMI list on conjur.org.
