### ISSUE TITLE
Need to decide when the build for this project gets run

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur-ami#5]
Every day? Every time commits are pushed to master in cyberark/conjur? Both?

**Comment by dustinmm80** [comment]
I think this makes most sense as a nightly build. We can 'bless' AMIs with version numbers, this can be nightly. Perhaps weekly later, if no one is using them

**Comment by dustinmm80** [comment]
@apotterri if you're okay with ^ suggestion can you close this issue? I think we can adjust as we go on this.

**Comment by apotterri** [comment]
Looks good to me.
